### PR TITLE
Use Assisticant in the WPF and Console examples

### PR DESCRIPTION
**Pull request by michaellperry**
Not looking for a merge, yet. Here's the branch in which I'm working on adding Assisticant to the demo.

### CODE REVIEW

**Comment by michaellperry** [comment]
I test-drove a domain model having teams with a manager and players. This model allows players to switch teams, and enforces the rule that a person can only play for one team.

My next step will be to test-drive the service broker. This class will sit off to the side and call a protocol (presumably a web API or data access layer) to load and save entities. It will be the only object to modify the domain model.

**Comment by michaellperry** [comment]
I'm trying to construct a service agent, but I can't get it to work. Could you take a look? There are two failing tests.

Furthermore, does everything need to be a Controller? In order for me to access the IO handler, it looks like I need to inherit from Controller. I want to call a Web API from the service agent, but I don't want all of the Controller stuff.

**Comment by michaellperry** [comment]
Here's a different approach. I created Major League Assisticant to show the Assisticant way of building an app. I'll highlight the parts that I think Miruken can really help out.

For example, at this point we have a set of DataTemplates in the App.xaml which map each view model to its view. You can see that this follows a pretty simple convention. I'm guessing that Miruken can implement this convention for me.

**Comment by michaellperry** [comment]
Next up, the IoC container. Miruken obviously has a different opinion on this. You'll see in a little bit why I prefer Autofac as my IoC.

**Comment by michaellperry** [comment]
Here, the NavigationModel is a singleton so that the view models can communicate with each other through a shared instance. This is what Assisticant does well. I should be able to put stuff like this high up in the context. Please help me figure that part out.

**Comment by michaellperry** [comment]
Here you start to see why I like Autofac. Notice how the `createTeamHeaderViewModel` function is injected into the `TeamsViewModel`. Autofac generates that function to contruct a new `TeamHeaderViewModel` from the supplied parameter and other objects from the context.

I use child view models like this whenever I have a collection. I don't like to bind directly to my models. Here, for example, you see how the `TeamHeaderViewModel` is transforming the coach and the manager from rich objects to strings. This kind of projection is almost always required, and it is much simpler to express when you have a child view model in between your view and your model.

**Comment by michaellperry** [comment]
Here's another place where Miruken could really add some value. I called the service agent from the view model to load the teams. I wrapped that in a `try ... catch` to control a couple of status properties. I'll bet that I can get Miruken to slap a decorator on that. Help, please?

**Comment by michaellperry** [comment]
I wasn't looking for a merge yet. Just a conversation.

**Comment by cneuwirt** [comment]
Cool, lets definitely discuss this next week.  Any day but tuesday

**Pull request merged**
